In [3]:
import numpy as np
a=np.array([7,6,4,2])
print(a)

[7 6 4 2]


In [5]:
import numpy as np
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]


In [9]:
c=np.arange(10)  #range of values in  array
d=np.linspace(1,5,6) #set of values by interval

print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


In [11]:
a=np.array([7,6,4,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim)  #Dimension of array
print(a.itemsize) #Byte size of each array
print(a.dtype)  #Datatype of array
print(a.size*a.itemsize)  #memory occupied - space occupied by 1 element
print(a.size) #number of elements in array
print(b.shape)  #shape of array(rows and columns)

1
4
int32
16
4
(2, 4)


In [13]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [15]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2]) #slicing the element from certian row and certain columns
print(b[0:,2])  #slicing the element from all rows adn certain column

9
[9 9]


In [19]:
e=np.array([7,9,9,2,16,11,96])
print(e.min()) #min element in array
print(e.max()) #max element in array
print(e.sum()) #sum of array

2
96
150


In [21]:
a=np.array([7,6,4,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0))#each elemennt of first dim array
print(b.sum(axis=1))#sum of all elements is 1st dim
print(np.sqrt(a))#squareroot of array elements
print(np.std(a))#std deviation of array
print(np.exp(a))#exponential of array
print(np.log(a))#natural log - ln
print(np.log10(a))#log base 10

[23 20 18  8]
[27 42]
[2.64575131 2.44948974 2.         1.41421356]
1.920286436967152
[1096.63315843  403.42879349   54.59815003    7.3890561 ]
[1.94591015 1.79175947 1.38629436 0.69314718]
[0.84509804 0.77815125 0.60205999 0.30103   ]


In [25]:
b=np.array([(7,9,9,2),(16,11,9,6)])
f=np.array([(1,2,3,4),(5,6,7,8)])

print(np.vstack((b,f))) #Vertical stack
print(np.hstack((b,f))) #Horizontal stack
print(b.ravel())#Merging as single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]


In [29]:
threeDarray=np.array([
        [[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [31]:
print(threeDarray[0][1][0])

4


In [33]:
print(threeDarray.dtype)

int32


In [35]:
nested_list=[1,2,3],[4,5,6]
for i in nested_list:
    for j in i:
        print(j)

1
2
3
4
5
6


In [37]:
threeDarray=np.array([
        [[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
for i in threeDarray.flatten():
    print(i)

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6


In [43]:
z=threeDarray.flatten()
print(z)
x=threeDarray.ravel()
print(x)

[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]


In [45]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [53]:
ones=np.ones(8)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
ones=ones.astype(int)
print(ones)

[1 1 1 1 1 1 1 1]


In [57]:
ranges=np.arange(5.6,9.8)
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [59]:
linspace=np.linspace(3,6,10)
print(linspace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [61]:
matrix=np.array([[76,34,89],[23,34,45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [63]:
print(matrix+2)

[[78 36 91]
 [25 36 47]]


In [65]:
print(matrix **2)

[[5776 1156 7921]
 [ 529 1156 2025]]


In [67]:
print(matrix.T)

[[76 23]
 [34 34]
 [89 45]]


In [69]:
print(matrix[1,])

[23 34 45]


In [77]:
print("1-D")
full=np.full(10,5)
print(full)

1-D
[5 5 5 5 5 5 5 5 5 5]


In [75]:
print("2-D")
full=np.full((2,2),10)
print(full)

2-D
[[10 10]
 [10 10]]


In [79]:
print("3-D")
full=np.full((2,5,4),5)
print(full)

3-D
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [81]:
pythonlist1=[[76,34,89],[23,34,45]]
pythonlist2=[[76,34,89],[23,34,45]]

In [83]:
pythonlist1+pythonlist2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [85]:
matrix1=np.array([[1,2,3],[4,5,6]])
matrix2=np.array([[7,8,9],[10,11,12]])


In [87]:
print(matrix1+matrix2)

[[ 8 10 12]
 [14 16 18]]


In [91]:
matrix1=np.array([[1,2,3],[4,5,6],[13,14,15]])
matrix2=np.array([[7,8,9],[10,11,12],[16,17,18]])
print(np.matmul(matrix1,matrix2))

[[ 75  81  87]
 [174 189 204]
 [471 513 555]]


In [93]:
marks=np.array([[87,90,89],[100,89,90],[94,77,90],[100,86,98]])

In [103]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())
print(round(marks.var(),2))

77
100
1090
90.83333333333333
6.242773600109348
38.97


In [101]:
print(marks.min(axis=1))
print(marks.max(axis=1))
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1)) #axis=1 means row

[87 89 77 86]
[ 90 100  94 100]
[266 279 261 284]
[88.66666667 93.         87.         94.66666667]
[1.24721913 4.96655481 7.25718035 6.18241233]


In [105]:
print(marks.min(axis=0))
print(marks.max(axis=0))
print(marks.sum(axis=0))
print(marks.mean(axis=0))
print(marks.std(axis=0)) #axis=0 means columnwise

[87 77 89]
[100  90  98]
[381 342 367]
[95.25 85.5  91.75]
[5.35607132 5.12347538 3.63145976]


In [109]:
np.append(x,(2,3))

array([ 1,  2,  3,  4,  5,  6, -1, -2, -3, -4, -5, -6,  2,  3])

In [115]:
n=np.array([1,2,3])
x=np.append([[1,2,3],[4,5,6]],[[1,2,3],n],axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [117]:
np.transpose(x)

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [119]:
x.T

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [123]:
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [125]:
arr>4

array([False, False, False, False, False,  True,  True])

In [127]:
arr[arr>4]

array([5, 6])

In [129]:
array=np.arange(12)

In [139]:
array.shape=(3,4)

In [135]:
np.arange(12).reshape((2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [141]:
np.random.rand(5)

array([0.4182052 , 0.64113021, 0.76136107, 0.89094811, 0.21787654])

In [143]:
np.random.randint(10,20,(5,5))

array([[12, 14, 12, 19, 12],
       [12, 10, 15, 15, 10],
       [12, 16, 13, 19, 17],
       [17, 14, 17, 10, 14],
       [18, 13, 19, 14, 18]])

In [145]:
letters=list('aeiou')
np.random.choice(letters,5)

array(['o', 'a', 'e', 'e', 'u'], dtype='<U1')

In [147]:
letters=list('aeiou')
np.random.choice(letters,5,replace=False)

array(['a', 'u', 'e', 'i', 'o'], dtype='<U1')

In [151]:
letters=list('aeiou')
np.random.choice(letters,5,p=[0.4,0.3,0.1,0.1,0.1])

array(['e', 'o', 'i', 'o', 'a'], dtype='<U1')

In [153]:
array=np.random.randint(10,20,(5,5))
np.save('array_file',array)

In [155]:
array2=np.load('array_file.npy')
print(array2)

[[16 18 15 15 15]
 [19 13 13 12 13]
 [15 12 14 19 17]
 [17 18 18 19 12]
 [16 17 13 13 18]]
